### ISSUE TITLE
[BUG] specific xposed / app not working

### ISSUE THREAD

**Issue by ghost** [refgd/BlackBox#3]
**Describe the bug** / **描述一下这个错误**
relate to #2
where cannot catch log using scoop
(scoop have xposed too for catch log

**To Reproduce** / **复现步骤**
1. just install and open app like usually then try to causing other app crash inside bb and now log not catched

**Expected behavior** / **预期的行为**
scoop / similar app should able to catch log via xposed

**Screenshots** / **截图**

**Mobile Phone Info** / **手机信息**
Realme 5i 
Android 10 Realme UI 1.0

**Logcat** / **日志**
N/A

**Additional context** / **额外内容**
1. idk which one isnt function either scoop app or xposed module
2. ig that not scoop dev fault this app was working on previous bb version (2.1.0)
3. tested on 2.1.2

**APK**

**Comment by refgd** [comment]
Please read #4

**Comment by ghost** [comment]
> Please read #4

nvm it working now on 2.1.3 thanks 🙏😊
@refgd
