### ISSUE TITLE
[Other]虚拟定位效果达到理想要求

### ISSUE THREAD

**Issue by BlackBoxing** [refgd/BlackBox#5]
虚拟定位预览版可以考虑为正式版，虽然还会有些不稳定，但是已经达到理想的要求了。有些信息发到你的谷歌邮箱了，看到了麻烦回下哈。

**Comment by refgd** [comment]
我试过, 比如这个App: https://play.google.com/store/apps/details?id=com.liuzh.deviceinfo, 并没有成功模拟地址, 这个APP获取的还是真实地址.

**Comment by BlackBoxing** [comment]
这些不用管，只要虚拟定位能达到理论效果就行了，有些app是用ip定位的，这个就不属于黑盒虚拟定位的管控范围内了。还有邮件记得回下。

**Comment by refgd** [comment]
做了更新, 在安卓12上面测试, 成功修改
