### ISSUE TITLE
[BUG] 最新的虚拟定位失效

### ISSUE THREAD

**Issue by crazyn2** [refgd/BlackBox#6]
**Describe the bug** / **描述一下这个错误**
清晰而简明地描述什么是错误。
虚拟定位失效。之前的虚拟定位在高德地图上还可以用，探探勉强凑合，你改了以后，高德地图读不到定位了，探探也没用了

**To Reproduce** / **复现步骤**

**Expected behavior** / **预期的行为**
清晰而简明地描述你所期望发生的事情。

**Screenshots** / **截图**
如果有，请添加屏幕截图以帮助解释你的问题。

**Mobile Phone Info** / **手机信息**
Xiaomi / Android 9

**Logcat** / **日志**
If you are a developer or capable please provide logs for us to analyze.
如果你是开发者或者有能力的请提供日志供我们分析。

**Additional context** / **额外内容**
在此添加关于该问题的任何其他内容。

**APK**
If applicable, add the apk file for me to test.
如果有，请添加APK文件给我测试。

高德地图，探探

**Comment by BlackBoxing** [comment]
他对这模块不是特别了解，体谅一下。先回退到原来的版本

**Comment by refgd** [comment]
有日志吗? 我在android 12上, 测试了高德, 虚拟定位是OK的

**Comment by crazyn2** [comment]
额，刚刚试试又可以了，就是探探地理位置一开始不是虚拟定位

**Comment by BlackBoxing** [comment]
这个也可能跟黑盒稳定性有关，迷失缺陷

**Comment by crazyn2** [comment]
可能是最新代码修复了，因为我拉了最新代码

**Comment by refgd** [comment]
嗯, 新的代码我还原了RequestLocationUpdates部分, Android 12并没有调用这个函数, 我只是凭android源码改了下, 没测试, 看来不兼容Android 9...
